# Generated by Django 3.2 on 2021-12-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='payment_slip',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
