# Generated by Django 3.2 on 2021-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_claim_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
